# Copyright (C) 2021 SCARV project <info@scarv.org>
#
# Use of this source code is restricted per the MIT license, a copy of which 
# can be found at https://opensource.org/licenses/MIT (or should be included 
# as LICENSE.txt within the associated archive or repository).


PROGRAM = ${SW}
BUILD   = ${REPO_HOME}/build/${SW}
EXTRA_SRCS := rv32zk.S
include ${SW_DIR}/common/common.mk









