# Copyright (C) 2021 SCARV project <info@scarv.org>
#
# Use of this source code is restricted per the MIT license, a copy of which 
# can be found at https://opensource.org/licenses/MIT (or should be included 
# as LICENSE.txt within the associated archive or repository).

TARGET ?= ${REPO_HOME}/src/hw/fpga/soc/crypto-ibex
FPGA    = $(REPO_HOME)/src/hw/fpga

PROGRAM = test-zks
BUILD   = ${REPO_HOME}/build
EXTRA_SRCS := rv32zks.S

HAL := ${TARGET}/hal
include ${HAL}/common.mk








